return {
  require("plugins.copilot"),
  require("plugins.copilotchat"),
  require("plugins.harpoon"),
  require("plugins.telescope-nvim"),
  require("plugins.nvim-tree"),
  require("plugins.git-blame-nvim"),
  require("plugins.black"),
  require("plugins.obsidian"),
  require("plugins.lualine-nvim"),
  require("plugins.nvim-autopairs"),
  require("plugins.nvim-cmp"),
  require("plugins.nvim-dap-python"),
  require("plugins.nvim-dap-ui"),
  require("plugins.nvim-dap-virtual-text"),
  require("plugins.nvim-lint"),
  require("plugins.nvim-lspconfig"),
  require("plugins.nvim-surround"),
  require("plugins.nvim-treesitter"),
  require("plugins.vim-commentary"),
  require("plugins.vim-maximizer"),
  require("plugins.vim-rest-console"),
}

